server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: nieat-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # =====================================
        - id: nieat-security-auth
          uri: lb://nieat-security-auth
          order: 8000
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: nieat-admin
          uri: lb://nieat-admin
          order: 8001
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=2
gateway:
  ignore:
    url: /auth/oauth/token